---
- name: Deploy CloudFormation stack using the template file
  cloudformation:
    stack_name: "tes3mp-ansible-test" 
    state: "present"
    region: "us-west-2" 
    disable_rollback: true
    template: "roles/deploy_cf_stack/files/template.yml"
  args:
    template_parameters:
      GameServerPassword: This is a really secure password
      StackUUID: "{{ 9999999 | random | to_uuid }}"
  register: stack
- name: show stack outputs
  debug: msg="Stack output:\n {{stack.stack_outputs}}"